import { useEffect, useState } from "react";
import { getBackupInfo } from "../services/backupService.js";

function Backup() {
  const [info, setInfo] = useState(null);
  const [error, setError] = useState("");
  useEffect(() => { getBackupInfo().then(setInfo).catch((requestError) => setError(requestError.message)); }, []);
  return <section><div className="page-header"><div><p className="eyebrow">Data protection</p><h1>Backup & data management</h1><p className="muted">Review backup status and follow the secure MongoDB Atlas procedure.</p></div></div>{error && <div className="notice error">{error}</div>}{!info ? <p className="empty-state">Loading backup information...</p> : <><div className="summary-grid"><div className="summary-card"><span>Status</span><strong>{info.status}</strong></div><div className="summary-card"><span>Automated backups</span><strong>{info.automatedBackupsSupported ? "Available" : "Manual"}</strong></div><div className="summary-card"><span>Last successful backup</span><strong>{info.lastSuccessfulBackup ? new Date(info.lastSuccessfulBackup.completedAt).toLocaleString("en-PH") : "None recorded"}</strong></div><div className="summary-card"><span>Collections</span><strong>{info.collections.length}</strong></div></div><div className="panel backup-instructions"><h2>Manual backup instructions</h2><p>{info.instructions.backup}</p><pre>{`mongodump --uri="$env:MONGODB_URI" --out="C:\\secure-backups\\rje-$(Get-Date -Format yyyyMMdd-HHmmss)"`}</pre><h2>Restore instructions</h2><p>{info.instructions.restore}</p><pre>{`mongorestore --uri="$env:MONGODB_URI" --drop "C:\\secure-backups\\YOUR-DUMP"`}</pre><p className="muted">The application does not execute backup or restore commands, does not accept arbitrary file paths, and never stores database credentials in backup metadata.</p></div><div className="panel"><div className="list-toolbar"><div><p className="eyebrow">Backup history</p><h2>Recorded backups</h2></div></div>{info.history.length === 0 ? <p className="empty-state">No backup records have been recorded.</p> : <div className="table-wrapper"><table><thead><tr><th>Started</th><th>Type</th><th>Status</th><th>Reference</th><th>Created by</th></tr></thead><tbody>{info.history.map((item) => <tr key={item._id}><td>{new Date(item.startedAt).toLocaleString("en-PH")}</td><td>{item.backupType}</td><td>{item.status}</td><td>{item.backupReference || "—"}</td><td>{item.createdBy?.name || "—"}</td></tr>)}</tbody></table></div>}</div></>}</section>;
}
export default Backup;
