import { useEffect, useState } from "react";
import { request } from "../services/api.js";

const API_URL = "http://localhost:5000/api/users";
const empty = { name: "", username: "", email: "", role: "staff", password: "" };
function Users() {
  const [users, setUsers] = useState([]); const [form, setForm] = useState(empty); const [editing, setEditing] = useState(null); const [search, setSearch] = useState(""); const [notice, setNotice] = useState({ type: "", text: "" }); const [isLoading, setIsLoading] = useState(true);
  const load = async () => { try { setIsLoading(true); setUsers(await request(API_URL)); } catch (error) { setNotice({ type: "error", text: error.message }); } finally { setIsLoading(false); } };
  useEffect(() => { load(); }, []);
  const submit = async (event) => { event.preventDefault(); try { await request(editing ? `${API_URL}/${editing._id || editing.id}` : API_URL, { method: editing ? "PUT" : "POST", body: JSON.stringify(editing ? { name: form.name, username: form.username, email: form.email, role: form.role } : form) }); setEditing(null); setForm(empty); setNotice({ type: "success", text: "User saved successfully." }); await load(); } catch (error) { setNotice({ type: "error", text: error.message }); } };
  const toggle = async (user) => { if (!window.confirm(`${user.isActive ? "Deactivate" : "Activate"} ${user.name}?`)) return; try { await request(`${API_URL}/${user.id || user._id}/status`, { method: "PATCH", body: JSON.stringify({ isActive: !user.isActive }) }); await load(); } catch (error) { setNotice({ type: "error", text: error.message }); } };
  const resetPassword = async (user) => { const password = window.prompt(`Enter a new password for ${user.name} (at least 8 characters):`); if (password === null) return; try { await request(`${API_URL}/${user.id || user._id}/reset-password`, { method: "PATCH", body: JSON.stringify({ password }) }); setNotice({ type: "success", text: "Password reset successfully." }); } catch (error) { setNotice({ type: "error", text: error.message }); } };
  const filtered = users.filter((user) => `${user.name} ${user.username} ${user.email}`.toLowerCase().includes(search.toLowerCase()));
  return <section><div className="page-header"><div><p className="eyebrow">Administration</p><h1>User management</h1><p className="muted">Manage access to the RJE system.</p></div></div>{notice.text && <div className={`notice ${notice.type}`}>{notice.text}</div>}<div className="products-layout"><form className="product-form" onSubmit={submit}><div className="form-heading"><h2>{editing ? "Edit user" : "Add user"}</h2>{editing && <button type="button" className="text-button" onClick={() => { setEditing(null); setForm(empty); }}>Cancel</button>}</div><label>Name<input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /></label><label>Username<input value={form.username} onChange={(event) => setForm({ ...form, username: event.target.value })} required /></label><label>Email<input type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} required /></label><label>Role<select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })}><option value="staff">Staff</option><option value="admin">Admin</option></select></label>{!editing && <label>Password<input type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} minLength="8" required /></label>}<button className="primary-button" type="submit">Save user</button></form><div className="panel product-list-panel"><div className="list-toolbar"><h2>Users</h2><input className="search-input" placeholder="Search users" value={search} onChange={(event) => setSearch(event.target.value)} /></div>{isLoading ? <p className="empty-state">Loading users...</p> : <div className="table-wrapper"><table><thead><tr><th>Name</th><th>Username</th><th>Email</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map((user) => <tr key={user.id || user._id}><td>{user.name}</td><td>{user.username}</td><td>{user.email}</td><td>{user.role}</td><td>{user.isActive ? "Active" : "Inactive"}</td><td className="actions"><button className="icon-button" onClick={() => { setEditing(user); setForm({ ...user, password: "" }); }}>Edit</button><button className="icon-button" onClick={() => toggle(user)}>{user.isActive ? "Deactivate" : "Activate"}</button><button className="icon-button" onClick={() => resetPassword(user)}>Reset password</button></td></tr>)}</tbody></table></div>}</div></div></section>;
}
export default Users;
